version: "3.8"

services:
  # App
  app:
    image: sapr-app
    build:
      context: .
    container_name: sapr-app
    depends_on:
      - db
      - imdb
    env_file:
      - ./docker/docker_env
    links:
      - db
      - imdb
    ports:
      - 80:80
    restart: always
    volumes:
      - ".:/var/www/html"

  # Database
  db:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: sapr-db
    env_file:
      - ./docker/docker_env
    ports:
      - 3306:3306
    volumes:
      - sapr-db:/var/lib/mysql

  # In-memory Database
  imdb:
    image: redis:6.0.3-buster
    container_name: sapr-imdb
    deploy:
      restart_policy:
        condition: any
    ports:
      - 6379:6379
    restart: always
    volumes:
      - sapr-imdb:/data

volumes:
  sapr-db:
  sapr-imdb: